### ISSUE TITLE
[Bug]: All Mono Scripts Missing

### ISSUE THREAD

**Issue by Piepop101** [ds5678/AssetRipper#101]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2019.4.21f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

I ripped a map from an old Blade and Sorcery Build of mine(.bundle) and the ripping process worked perfectly EXCEPT all scripts were missing(Despite the original scripts being in the project).

<img width="208" alt="Screenshot Region 295" src="https://user-images.githubusercontent.com/65717644/134776083-1e289c9f-16e1-4a7e-b28a-e6d925156d36.png">

### Relevant log output

[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7229998/AssetRipper.log)

**Comment by ds5678** [comment]
I have written a detailed explanation to your issue in #102
