### ISSUE TITLE
[FAQ]: Why doesn't AssetRipper export Mono Scripts from my bundle?

### ISSUE THREAD

**Issue by ds5678** [ds5678/AssetRipper#102]
### Describe the issue

Except in extremely rare and special cases, there are no mono scripts stored in asset bundles. 

Mono scripts are stored in C# assemblies, ie `.dll` files. The contents of these assemblies can be viewed in [ILSpy](https://github.com/icsharpcode/ILSpy).

> Note: C++ assemblies also use the `.dll` extension. If C# code can't be viewed after opening a `.dll` file in ILSpy, then it's not a C# assembly.

In order to export mono scripts with asset bundle assets, the relevant assemblies must be included in the import. You can do this by: 
1. Place all the assemblies in a folder. 
2. Select that folder and the assetbundle(s) being ripped. 
3. Drag those into AssetRipper at the same time.

If it worked, you'll get this line in the log:
```
Import : Files use the 'Mono' scripting backend.
```
If it didn't work, there will be this line:
```
Import : Files use the 'Unknown' scripting backend.
```

For IL2Cpp games, use [Cpp2IL](https://github.com/SamboyCoding/Cpp2IL) to generate assemblies. [Unhollowed assemblies](https://github.com/knah/Il2CppAssemblyUnhollower) used in modding will not work.

**Comment by ds5678** [comment]
@Piepop101 Have you considered joining the [Discord server](https://discord.gg/XqXa53W2Yh)? We have lots of conversation about bugs, development, etc. My response time there is normally better, and other users also have the opportunity to help you too.

From your log, it seems you did things correctly and were disappointed with the results. Your screenshot shows relatively normal behavior for deleting things that have references attached.

**Comment by Piepop101** [comment]
Oh I'm so sorry, I didn't realize there was a discord server..... Thanks!

**Comment by ds5678** [comment]
This has been moved to https://ds5678.github.io/AssetRipper/articles/CommonIssues.html

**Comment by arcomsians** [comment]
![issue](https://user-images.githubusercontent.com/116951660/198833449-96929cec-49db-4d56-ac1c-230596029b91.PNG)
Why function miss in each script use AssetsRipper

**Comment by arcomsians** [comment]
> ![issue](https://user-images.githubusercontent.com/116951660/198833449-96929cec-49db-4d56-ac1c-230596029b91.PNG) Why function miss in each script use AssetsRipper

please guide me

**Comment by TS-DEV-DEBUG-V2** [comment]
@arcomsians If the game was il2cpp (says Import : Files use the 'il2cpp' scripting backend)
well il2cpp cant be decompiled (the only way is to use ghidra on GameAssembly.dll and get pseudo code and manually reconstruct/rewrite the game

So what AssetRipper does
it uses Cpp2IL
which just outputs function names 
and other metadata.
