### ISSUE TITLE
Magic number doesn't match

### ISSUE THREAD

**Issue by CyberAndrii** [ds5678/AssetRipper#11]
### Are you on the latest version of AssetRipper?

- [X] Yes, I'm on the latest commit from `master` branch.

### Which release are you using?

Console Version Windows x64

### Which game did this occur on?

Game: Unturned
Game's Unity version: 2019.4.28

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Crashes when exporting `Framework/SpeedTree Billboard` shader.

You can use this file to try yourself:
[unity_builtin_extra.zip](https://github.com/ds5678/AssetRipper/files/6880992/unity_builtin_extra.zip)

### Relevant log output

[AssetRipperConsole.log](https://github.com/ds5678/AssetRipper/files/6881005/AssetRipperConsole.log)

**Comment by ds5678** [comment]
I suspect that this is probably related to #5 and the broader compatibility issues facing newer Unity versions. I am currently in the middle of reworking the import system to address these issues. If this is still non-working after the update, we'll revisit this and investigate the causes.

**Comment by ds5678** [comment]
@CyberAndrii are you still having this error on the latest alpha build?

**Comment by CyberAndrii** [comment]
Not anymore.
