### ISSUE TITLE
[Bug]: Why mono scripts doesn't work?

### ISSUE THREAD

**Issue by Vilisskiss** [ds5678/AssetRipper#124]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

Unity 2018.4.22f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Why mono scripts doesn't work?
![Screenshot_1](https://user-images.githubusercontent.com/86745648/135712576-b14bb636-a604-41ab-8f3f-24dc4ff5b103.png)

**Comment by ds5678** [comment]
I need a log in order to help you at all.

**Comment by Vilisskiss** [comment]
[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7271979/AssetRipper.log)

**Comment by ds5678** [comment]
Duplicate of #102

**Comment by Vilisskiss** [comment]
how fix it?
