### ISSUE TITLE
[Bug]: cann't extract

### ISSUE THREAD

**Issue by KrevetkaOo** [ds5678/AssetRipper#126]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Console Version Windows x64

### Which Unity version did this occur on?

Unity 2019.4.31f1 (64-bit)

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

file to test: [click me](https://github.com/ds5678/AssetRipper/files/7274440/ava.zip)

### Relevant log output

[AssetRipperConsole.log](https://github.com/ds5678/AssetRipper/files/7274439/AssetRipperConsole.log)

**Comment by ds5678** [comment]
The AssetRipper development team does not offer technical support for ripping VR Chat or content intended for VR Chat.
