### ISSUE TITLE
[Enhancement]: Debug support

### ISSUE THREAD

**Issue by FreeBSoD** [ds5678/AssetRipper#14]
### Describe the new feature or enhancement

What I mean with this is, if you decompile it, the program checks for any errors in the .CS files.

**Comment by ds5678** [comment]
What kind of errors? What would it do when it found these errors?

**Comment by FreeBSoD** [comment]
errors from the CS files, like syntax errors

**Comment by ds5678** [comment]
I don't think there's anything I could do that would work better than opening the project in an IDE afterwards.

Rather than checking for errors, how about we approach this from a different angle. AssetRipper generates the CS files. Is there a bug you noticed in code generation?

**Comment by FreeBSoD** [comment]
yeah, once i did it (this was like 4 days ago) it generated empty CS files. But now it does not. maybe it was or is a bug

**Comment by ds5678** [comment]
It only outputs the serializable fields. This is intended to reduce compile errors

**Comment by ds5678** [comment]
Have you been able to reproduce any CS file output bugs?
