### ISSUE TITLE
[Bug]: AssetRipper Crash

### ISSUE THREAD

**Issue by RumitKmphitech** [ds5678/AssetRipper#141]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version MacOS x64

### Which Unity version did this occur on?

Unity Version 2021

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Hi Bro First of all Thank you very much To Create a Asset Ripper .....
and Again My Qus Is assets Ripper are Windows OS perform is very perfectly but this assets are MacOs Not Open Setup So Please Resolve This Issues. Thank You Very much Again

**Comment by ds5678** [comment]
If I understand you correctly, you're having difficulty opening the Mac version. You may have to use `chmod +x` on it to make it executable.
