### ISSUE TITLE
[Enhancement]: Configure script decompiler language version

### ISSUE THREAD

**Issue by xmqf** [ds5678/AssetRipper#144]
### Describe the new feature or enhancement

Currently the script decompiler seems to be hardcoded to C# version 7.3 in the ScriptDecompiler class:
```
DecompilerSettings settings = new DecompilerSettings();
settings.SetLanguageVersion(LanguageVersion.CSharp7_3);
```
This makes it impossible to use for the older Unity games that don't support C# 7, as you end up with the project that won't compile. And upgrading Unity itself isn't always an option either, since keeping the exact same version may be essential for game modding purposes. It would be nice to have an option to pass the custom C# version to the AssetRipper before decompiling.

**Comment by ds5678** [comment]
Exposed to the GUI in ddcb605fbf49cb574aaeaca03b86c4924f9d5764
