### ISSUE TITLE
[Bug]: AssetRipper does not handle detecting if a resource file is binary or text.

### ISSUE THREAD

**Issue by NotAika** [ds5678/AssetRipper#156]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

5.4.2f2

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

AssetRipper seems to not handle/detect when a resource file is text or binary, for example: Beat Saber Origins uses MIDIs for its song data, when you attempt to export it as a Unity project it will export those MIDIs as ".txt" instead of ".bytes". This means that anytime that game attempts to read those MIDIs, it'll likely cause a stream exception as it's not being recognized as binary.

**Comment by ds5678** [comment]
Interesting. I didn't realize some games stored non-text data as a TextAsset

**Comment by ds5678** [comment]
This should have been implemented in cc75c012d4a7e7bb3900c8a64edbacab1904de25
