### ISSUE TITLE
[Other]:  I cant build the code in Microsoft Visual Code

### ISSUE THREAD

**Issue by Ripper0123** [ds5678/AssetRipper#167]
### Describe the issue

It say's build failed, idk if you did something wrong and im trying to extract Phasmophobia

**Comment by Ripper0123** [comment]
I cant have an exe file IF i dont build it

**Comment by ds5678** [comment]
I have Windows and Linux. I've compiled AssetRipper on both without issue on all 3 major IDE's (Visual Studio, Visual Studio Code, and JetBrains Rider). If you're having issues compiling with VS Code, it's probably one or more of the following things:
* You need to install .NET 6
* You need to add the official C# extension to VS Code
* You need to setup your `tasks.json` in VS Code

Alternatively, if you only need an executable, you could just download a release.
