### ISSUE TITLE
[Bug]: Bundle Files

### ISSUE THREAD

**Issue by Piepop101** [ds5678/AssetRipper#17]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Console Version Windows x64

### Which Unity version did this occur on?

2019.4.21f1

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

<img width="290" alt="Screenshot Region 72" src="https://user-images.githubusercontent.com/65717644/127780799-00bdc4bb-a73c-46bc-83d7-4b86990d635d.png">

### Relevant log output

[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/6913137/AssetRipper.log)

**Comment by ds5678** [comment]
Hi, this is a duplicate of #5. Whenever I resolve it, this should be fixed too.

**Comment by ds5678** [comment]
Hi, this should have been resolved in a recent commit
