### ISSUE TITLE
[Bug]: VERY slow extraction for small files

### ISSUE THREAD

**Issue by lab313ru** [ds5678/AssetRipper#173]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2019.2.6

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Extraction process starts fast, but then it slows down a lot at many small files that are ScriptableObject's. Such files count is ~99k. The game is `Sally Face`.
The extraction process slows down at ~50% and goes as 1 file per second, when a file size is ~200 bytes.

### Relevant log output
[AssetRipper.zip](https://github.com/ds5678/AssetRipper/files/7587740/AssetRipper.zip)

**Comment by lab313ru** [comment]
The same happens with uTinyRipper, but it produces files like `(Clone)(Clone)(Clone)(Clone)(Clone)(Clone)(Clone)(Clone)(Clone)(Clone)(Clone)(Clone)(Clone)(Clone)(Clone)(Clone)(MonoBehaviour)` in their names, and `AssetRipper` does that in the log.

**Comment by ds5678** [comment]
Performance issues are often difficult to debug on Github. If you join the [Discord server](https://discord.gg/XqXa53W2Yh), we'll profile this to identify any areas that could be improved.

AssetRipper automatically removes `(Clone)` from outputted file names for clarity and to avoid going over 250 characters in the output path.
