### ISSUE TITLE
[Bug]: Broken OGG files

### ISSUE THREAD

**Issue by lab313ru** [ds5678/AssetRipper#179]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2019.2.6

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

The game "Sally Face" produces FSB files that cannot be converted to correct OGG files.
Also, it looks like in some cases multi threading breaks valid OGG files producing too.

Example of a valid FSB file with a broken OGG in result: [gearBoy_BootUp.zip](https://github.com/ds5678/AssetRipper/files/7602963/gearBoy_BootUp.zip)
Example of a valid FSB file with a broken OGG after multithread access to vorbis libs: [ghostScream.zip](https://github.com/ds5678/AssetRipper/files/7602972/ghostScream.zip)

**Comment by lab313ru** [comment]
Let it be here too: https://gist.github.com/lab313ru/54a9b77d10e8b81c9cef2ac6340563f7
My implementation, that just work.

**Comment by ds5678** [comment]
@lab313ru this is an upstream issue. Please redirect all discussion to SamboyCoding/Fmod5Sharp#2
