### ISSUE TITLE
[Bug]: Failed to load game content: Error during reading of asset type Shader

### ISSUE THREAD

**Issue by pavel1337228** [ds5678/AssetRipper#180]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2017.4.30f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Error during reading of asset type Shader

### Relevant log output

[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7610293/AssetRipper.log)

**Comment by ds5678** [comment]
I am currently working on a generalized solution #164
