### ISSUE TITLE
[Feature]:  PSVita Support

### ISSUE THREAD

**Issue by BurAndBY** [ds5678/AssetRipper#181]
### Describe the new feature or enhancement

PSVita VPK's don't work at all. 

Example of game structure:
![image](https://user-images.githubusercontent.com/48630651/143676147-67a8eb57-b2c4-4317-9a91-184649808651.png)
Default Unity Game Structure is located at *.VPK\Media\
![image](https://user-images.githubusercontent.com/48630651/143676164-6b2b5d3e-c57f-49d1-a9d2-27ec7fb62047.png)

**Comment by ds5678** [comment]
This should be implemented in 1046c73907af4ef79719ad895fbbbf6f9a871ff9. If not, reopen
