### ISSUE TITLE
il2cpp support for another platform

### ISSUE THREAD

**Issue by vale7z4387ruwrejmhsr** [ds5678/AssetRipper#186]
### Describe the new feature or enhancement

hi ds5678 could you also add IL2Cpp Support for android games?
because you already added support for decompiling il2cpp code for switch
so why not do it with android

**Comment by SamboyCoding** [comment]
Ripper already supports android il2cpp games.

**Comment by vale7z4387ruwrejmhsr** [comment]
but when i put the lib2cpp.so file and the global-metadata.dat file in that one folder it says files use the unknown scripting backend

**Comment by ds5678** [comment]
AssetRipper only searches in the correct locations for those files. If you're moving the files, that would explain why they're not being found

**Comment by vale7z4387ruwrejmhsr** [comment]
ok
