### ISSUE TITLE
[translation]: 

### ISSUE THREAD

**Issue by vale7z4387ruwrejmhsr** [ds5678/AssetRipper#191]
### Describe the new feature or enhancement

i translated the program into german for localization of course
[de_DE.txt](https://github.com/ds5678/AssetRipper/files/7649397/de_DE.txt)

**Comment by SamboyCoding** [comment]
Please submit your translations via the [Weblate](https://weblate.samboy.dev/projects/assetripper/gui/de/) portal

**Comment by vale7z4387ruwrejmhsr** [comment]
done

**Comment by ds5678** [comment]
#192 has been merged so you should be able to see your translations in the latest alpha
