### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gkimset** [ds5678/AssetRipper#195]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2020.3.16f1c1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

SerializedFileException: v:2020.3.16f99 p:Android t:Texture2D n:unity default resources

### Relevant log output

[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7660987/AssetRipper.log)

**Comment by ds5678** [comment]
You compiled with the DebugLinux configuration instead of ReleaseWindows.

If you just wanted the latest alpha, you can download it here:

https://ds5678.github.io/AssetRipper/articles/Downloads.html

**Comment by gkimset** [comment]
[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7664201/AssetRipper.log)
Thanks, but there are still bugs

**Comment by ds5678** [comment]
Given a version of `2020.3.16f99`, I suspect your game may be using a custom unity engine. However the latest alpha is far more forgiving of asset read errors, which are being addressed in #164.
