### ISSUE TITLE
Bug: Crash On Asset Load -> Valeheim Unity 2019.4.24

### ISSUE THREAD

**Issue by sbtoonz** [ds5678/AssetRipper#2]
**Describe the bug**
Load Asset files into AssetRipper in same method I would use UTiny, Instant crash

**To Reproduce**
1) Open Program
2) drop game folder where it directs
3) watch crash

**Expected behavior**
AssetRipper to export the unity project version of my assets in similar manner to Utiny

**Error Message**
There is no saved logoutput and i am unable to copy the logoutput from the app

**Information (please complete the following information):**
Windows 10 home
Unity 2019.4.24

**Additional context**

**Comment by ds5678** [comment]
There should be a file called `AssetRipper.log` in the same directory as `AssetRipper.exe`. I need that file from you

**Comment by sbtoonz** [comment]
This file does not populate with output

**Comment by sbtoonz** [comment]
its 0 bytes in size i will film this, the error message does not seem to populate the log and i haven't looked at source to try and isolate or add debugging to figure out the break point

**Comment by sbtoonz** [comment]
https://youtu.be/FPLYX6VcBwk

**Comment by ds5678** [comment]
So `2019.4.24`. I think your game uses the Addressable system. Later versions of Unity 2019 support it. I'll be doing another release sometime in the near future with better logging. If you join the Discord server, we can debug the crashing together.

**Comment by soargon** [comment]
> So `2019.4.24`. I think your game uses the Addressable system. Later versions of Unity 2019 support it. I'll be doing another release sometime in the near future with better logging. If you join the Discord server, we can debug the crashing together.

why disable debug symbol output?

**Comment by ds5678** [comment]
@soargon is there a specific commit you're referring to?

**Comment by soargon** [comment]
@ds5678 [this line](https://github.com/ds5678/AssetRipper/commit/18e1287436df36dde93e9f3d657f71495242ff03#r53847773)

**Comment by ds5678** [comment]
@soargon that's not really relevant to this issue, but it made it easier to copy and paste things. What is your interest in it?

**Comment by soargon** [comment]
@ds5678 oh, i cloned this repo a moment ago, in order to read the code to start debug the program and then I found that there are no debug symbols, its desnt matter.  I am interested in contributing to this project, how to join Discord?

**Comment by ds5678** [comment]
https://discord.com/

After you've made an account, you can just click the invite link in my readme.

**Comment by ds5678** [comment]
This was resolved in [`0.1.2.0`](https://github.com/ds5678/AssetRipper/releases/tag/0.1.2.0). If you encounter something similar, please post a new issue.
