### ISSUE TITLE
[Bug]: Read Asset Regression

### ISSUE THREAD

**Issue by MrGrizzzzly** [ds5678/AssetRipper#22]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2013.4.2.2f11

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Not exporting AnimatorController - not supporting older versions unity.
https://drive.google.com/file/d/187wRY4QCM2_eXR3f3alTMmxpc0Qnc_zk/view?usp=sharing

### Relevant log output

[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/6950892/AssetRipper.log)

**Comment by ds5678** [comment]
This is unfortunate. It appears that I introduced a regression at some point. I'll see if I can resolve it.

**Comment by MrGrizzzzly** [comment]
> ### Are you on the latest version of AssetRipper?
> Yes, I'm on the latest release of AssetRipper.
> 
> ### Which release are you using?
> GUI Version Windows x64
> 
> ### Which Unity version did this occur on?
> Unity version old 2013.4.2.2f11.
> 
> ### Is the game Mono or IL2Cpp?
> Mono
> 
> ### Describe the issue.
> Not exporting animations - the probable reason is not supporting animations older versions unity.
> https://drive.google.com/file/d/187wRY4QCM2_eXR3f3alTMmxpc0Qnc_zk/view?usp=sharing
> 
> ### Relevant log output
> [AssetRipper.log](https://github.com/ds5678/AssetRipper/files/6950892/AssetRipper.log)

**Comment by ds5678** [comment]
This is being addressed in #164
