### ISSUE TITLE
[Bug]: Shader Blob Decompression is incorrect for Unity 2020

### ISSUE THREAD

**Issue by SamboyCoding** [ds5678/AssetRipper#28]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2020.2 at least, probably 2020.1 too.

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

The method `Shader.UnpackSubProgramBlobs` incorrectly separates blobs on Unity 2020. The output is too long and has incorrect offsets, resulting in this sort of problem.
![image](https://user-images.githubusercontent.com/7011721/128900597-307b9ccd-a5f1-461a-b1d3-d3a4c6722890.png)
Pictured is the input to the Smol-V decoder, which contains two "SMOL" header magic numbers, neither of which are actually at the start of the input. Presumably there is a third prior to where the data starts in this image.

It's possible that the format of the compressed blob has changed somehow, or, more probably (considering that valid text is present in the result data, both the SMOL header and the GLSL version) the offsets and lengths no longer behave as they used to, resulting in a failure to divide the blob into sub-programs correctly.

**Comment by ds5678** [comment]
In 955d00f899abb8af2d6daf10aa07bf6855bb05fb, I completely removed the shader disassembly code, so this issue no longer reflects the current state of the project. Shader export is being replaced with an enhanced dummy shader system, which should be far more manageable and compatible with future plans for the project.
