### ISSUE TITLE
[Bug]: Shader Export Problem

### ISSUE THREAD

**Issue by janes-l** [ds5678/AssetRipper#32]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

by unity 2019.2.13

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

 **Export no problem，but the first 4 shaders content is empty, other shader properties are different, the content of the sub-shader is the same.
Pls help me!**

### Relevant log output

no log

**Comment by ds5678** [comment]
Can you upload the bad shaders here?

**Comment by janes-l** [comment]
[Shader.zip](https://github.com/ds5678/AssetRipper/files/6973266/Shader.zip)

**Comment by janes-l** [comment]
This is the shader I exported with the latest release version

**Comment by ds5678** [comment]
The first 4 shaders being empty is bizarre.

All the other shaders are just dummy shaders meant to compile correctly.

**Comment by janes-l** [comment]
I tried several times and the result is still the same.
Can other shaders be restored to what they were before compilation?

**Comment by ds5678** [comment]
Shader disassembly is very difficult. This is an intermediate solution to provide compileable shaders.

**Comment by ds5678** [comment]
The empty shader issue should be resolved at this time. If your problem persists, feel free to post a new issue.
