### ISSUE TITLE
[Bug]: Error during reading of asset type Shader

### ISSUE THREAD

**Issue by MarshMello0** [ds5678/AssetRipper#33]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2020.3.11f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Thank you @ds5678 and @SamboyCoding for the 2020 support. I had a go at it today and there seems to be an issue with reading a shader from the unity default resources file.

[unity default resources.zip](https://github.com/ds5678/AssetRipper/files/6973236/unity.default.resources.zip)

### Relevant log output

[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/6973226/AssetRipper.log)

**Comment by ds5678** [comment]
This is a struct match issue. During our testing, we only went up to `2020.2.0`. Somewhere between it and your version, the struct format changed.

**Comment by MarshMello0** [comment]
I had tested it on the merge request when you created it yesterday before it got merged and it worked fine thanks. 
I haven't tested it on the latest commit but I assume it still will work.
