### ISSUE TITLE
[Bug] Issue extracting game scripts on Android IL2Cpp

### ISSUE THREAD

**Issue by DatTaiwanGuy** [ds5678/AssetRipper#4]
Hi,

can you make the tool also decompile scripts and then also import them to Unity project just like DevX Game Recovery, MagicStudio and UnpackerTools? (They always do that using some different decompiler such as dnSpy and DecompilerFi then they import it to a Unity Project)

**Comment by ds5678** [comment]
Both uTinyRipper and AssetRipper export scripts to the Unity project. How is this different from that?

**Comment by DatTaiwanGuy** [comment]
Cause when i opened a ripped game project ripped from Rockman X DiVE using utinyripper, my editor says that it's missing some scripts and scripts which have dll's like System.Reflections, CapCommon, CallbackDefs, e.t.c and other scripts which have necessary extensions from the game like CriMana(except for Unity's built-in ones like Unity.Burst, Unity.Mathematics, Unity.Jobs and others)

**Comment by ds5678** [comment]
Is your game Mono or IL2Cpp?

**Comment by DatTaiwanGuy** [comment]
IL2Cpp..

**Comment by ds5678** [comment]
Try again with `0.1.3.0`. I just added IL2Cpp support.

**Comment by DatTaiwanGuy** [comment]
![image](https://user-images.githubusercontent.com/81352397/126866701-6813c39e-dd3b-464f-baf2-e009ca09a2a3.png)
is this normal for the program?

**Comment by ds5678** [comment]
I am unfamiliar with the Android file structure for IL2Cpp games. This is probably a simple fix. It's just not recognizing the game as IL2Cpp because it can't find the `GameAssembly.dll` file.

**Comment by DatTaiwanGuy** [comment]
Okay, it has detected that it's using 'Mono' scripting backend from lLL2CPP binary file, now what 
![image](https://user-images.githubusercontent.com/81352397/126896075-62cad5c8-2119-49ba-8aab-c4b49c94d683.png)

**Comment by ds5678** [comment]
Are you able to compile from the source? I just pushed some changes that I think might solve this issue, and I want to know if it works for you.

**Comment by DatTaiwanGuy** [comment]
Same issue......
![image](https://user-images.githubusercontent.com/81352397/126900397-7fc26da3-8120-45d0-a394-f2159073f00c.png)

**Comment by ds5678** [comment]
That might be from source, but it's not the most updated source. I can tell because I changed some of the log statements and you don't have those changes. I'm going to publish a pre-release in a few minutes for you to try.

In the future, instead of taking screenshots, please include your `AssetRipper.log` file. It's in the same folder as the exe. You just drag and drop it into the textbox.

**Comment by ds5678** [comment]
I just pre-released [0.1.3.1](https://github.com/ds5678/AssetRipper/releases/tag/0.1.3.1)

**Comment by ds5678** [comment]
continued in #7
