### ISSUE TITLE
[Bug]: The program is terminated as soon as the export button is clicked

### ISSUE THREAD

**Issue by ntdcpk** [ds5678/AssetRipper#42]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

 During Il2Cpp initialization, found Unity version: 2019.2.19

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

The program is terminated as soon as the export button is clicked.

**Comment by ds5678** [comment]
We have recently replaced the GUI program, so any bugs you find on the `0.1.4.0` release might not be relevant anymore.

You are welcome to try the latest alpha build from the [Actions page](https://github.com/ds5678/AssetRipper/actions). I would be interested to know if your problem persists.

**Comment by ds5678** [comment]
Are you still having this issue on the latest alpha?

**Comment by ds5678** [comment]
If your problem still persists on the latest release, please feel free to post a new issue.
