### ISSUE TITLE
[Enhancement]: Fix script decompilation

### ISSUE THREAD

**Issue by Kiffolisk** [ds5678/AssetRipper#49]
### Describe the new feature or enhancement

Mono code currently does not decompile correctly (only decompiles some fields but nothing else). Yes, you can technically use dnSpy to copy-paste the code back in, but it takes too long to do, considering most projects have tons of scripts.

**Comment by ds5678** [comment]
Hello! Creating a full decompiler is complicated and out of the scope of this project. Unless you can present some NuGet package options for exporting a Mono.Cecil `TypeDefinition`, this is not a feature I'm likely to add.

**Comment by Kiffolisk** [comment]
From what I know, dnlib can.

**Comment by ds5678** [comment]
dnlib is not compatible with Mono.Cecil and only supports Dll export (which Mono.Cecil also has). I would need a package that extends Mono.Cecil for text file output.

**Comment by ds5678** [comment]
I've posted an issue about this feature: #65
