### ISSUE TITLE
[Bug]: Nintendo Switch Game Error

### ISSUE THREAD

**Issue by antim0118** [ds5678/AssetRipper#52]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Console Version Windows x64

### Which Unity version did this occur on?

2019.4.16f1

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

`Specified method is not supported` appears when it starts bulding files for ProjectSettings folder.
Game is NEO Twewy for Nintendo Switch.

### Relevant log output

[AssetRipperConsole.log](https://github.com/ds5678/AssetRipper/files/7015422/AssetRipperConsole.log)

**Comment by ds5678** [comment]
I just pushed a more descriptive error message. Can you try again and send me the new error message?

**Comment by antim0118** [comment]
> I just pushed a more descriptive error message. Can you try again and send me the new error message?
[AssetRipperConsole.log](https://github.com/ds5678/AssetRipper/files/7016333/AssetRipperConsole.log)

**Comment by ds5678** [comment]
I just pushed a fix. Tell me how it goes for you

**Comment by antim0118** [comment]
Now it works but for unknown reason it skips some assets. I didn't tried to use newer version (after [bundle extension](https://github.com/ds5678/AssetRipper/actions/runs/1148127772) commit), I will try again later.
I have a question. Is it ok if I have no scripts (.cs files) in project folder? When I was ripping mono game it had scripts, but not on IL2CPP.

**Comment by ds5678** [comment]
The reason is that I can't implement IL2Cpp Switch support without having an IL2Cpp Switch game to test on, so it treats things as if there are no scripts at all.

**Comment by ds5678** [comment]
I have a program to log the internal file structure of a game.
https://github.com/ds5678/RelativePathLogger
If you drop your IL2Cpp switch game onto it, it'll create a text file. That file should allow me to add IL2Cpp support for switch.

**Comment by antim0118** [comment]
> If you drop your IL2Cpp switch game onto it, it'll create a text file. That file should allow me to add IL2Cpp support for switch.

[Output.txt](https://github.com/ds5678/AssetRipper/files/7071066/Output.txt)

**Comment by ds5678** [comment]
This looks like it's just the data folder not the full game. I need the game folder. The game folder should contain a folder called `romfs`.

**Comment by antim0118** [comment]
> This looks like it's just the data folder not the full game. I need the game folder. The game folder should contain a folder called `romfs`.

That's literally the romfs folder. I spent a couple of days to verify this.

**Comment by ds5678** [comment]
I need the game folder dropped onto the relative path logger.

The game folder contains `romfs`.
`romfs` contains `Data`.
`Data` contains `globalgamemanagers`, all the level files, the `Managed` folder, etc.

Without the game folder, there's nothing I can do for this because the files I need to see are outside of the folder you logged.

**Comment by antim0118** [comment]
Oh, I thought I logged wrong folder.
Here's the game files https://disk.yandex.ru/d/ApJ54Ep7u545kg

**Comment by ds5678** [comment]
Thank you. That was exceedingly useful for analyzing this.

Unfortunately, the il2cpp binary executable type used for switch games is not supported by Cpp2IL. Until such support has been added, there is nothing I can do.
