### ISSUE TITLE
[Enhancement]: Can you retain the compilation of Shader pseudo code?

### ISSUE THREAD

**Issue by Shiyaemetu** [ds5678/AssetRipper#57]
### Describe the new feature or enhancement

Sorry, I use the translator
I found that the latest version does not export shader's pseudo code
But use a fake shader instead
I know this is used to solve the error in the project.
But I need to view pseudo code to make Decompile for some simple shader.
So can I retain the function of exporting pseudo code make him an option?

**Comment by ds5678** [comment]
The pseudo code feature is not removed, just disabled. You can re-enable it by changing a variable [here](https://github.com/ds5678/AssetRipper/blob/master/AssetRipperLibrary/Configuration/LibraryConfiguration.cs) and recompiling.

**Comment by Shiyaemetu** [comment]
> The pseudo code feature is not removed, just disabled. You can re-enable it by changing a variable [here](https://github.com/ds5678/AssetRipper/blob/master/AssetRipperLibrary/Configuration/LibraryConfiguration.cs) and recompiling.

I understand, thank you for your reply.

**Comment by ds5678** [comment]
Good luck :)
