### ISSUE TITLE
[Bug]: Missing MonoBehaviour script on prefab

### ISSUE THREAD

**Issue by dc7777777** [ds5678/AssetRipper#59]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2019.4.20f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Game Totally Accurate Battle Simulator
![clipboard(1)](https://user-images.githubusercontent.com/70512714/130934921-ad401025-d6fc-43a1-8493-328e53b0ca8a.png)
left file is export from UtinyRipper, right is from AssetRipper

ProjectSettings/ProjectVersion.txt show m_EditorVersion: 2017.3.0f3，the unity version should be 2019.4.20f1

### Relevant log output

[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7055751/AssetRipper.log)

**Comment by ds5678** [comment]
Hello, thank you for reporting the bug. We discovered that it affected most games and have resolved the script reference bug in `0.1.5.1`.

Unfortunately, we also discovered that your game was compiled in a non-release format, so it may not export now that this bug has been patched.

**Comment by ds5678** [comment]
I've posted an issue about Non-Release games (#64). If you have any persisting issues not covered by that, feel free to post a new issue.
