### ISSUE TITLE
[Enhancement]: Allow dummy shaders conversion back to ShaderLab for Unity Editor (also allow support of CAB 'decompressed' files from AssetStudio to AssetRipper)

### ISSUE THREAD

**Issue by DatTaiwanGuy** [ds5678/AssetRipper#6]
### Are you on the latest version of AssetRipper?

- [X] Yes, I'm on the latest version of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

Game: ROCKMAN X DiVE
Engine: Unity 2018.4.27f1
Platform: Android/iOS (soon to be ported to PC/Steam cause of some news from the rockman corner)

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Well i tried to extract the game assets using your tool, but it dosent seem to detect the decompressed CAB files that i used using AssetStudio from the assets(even when i drag 'n' dropped the folder). Is there something oddly missing, are the CAB files misplaced, is the base apk split?

I mean 
![image](https://user-images.githubusercontent.com/81352397/126893251-18264029-bd77-4b27-bf93-ef917e387231.png)
these are the CAB files that i decompressed from the assets using Perfare's AssetStudio, but in AssetRipper, it doesn't show anything except the base apk ones 
![image](https://user-images.githubusercontent.com/81352397/126893307-8b20cfea-e6dd-4d2d-a361-f923011d6679.png)

their size is 1.88 GB decompressed from the game's server:
![image](https://user-images.githubusercontent.com/81352397/126893356-806bec78-c46a-4fa6-933d-cca4fce3fc26.png)

Also, about the shaders that i extracted with your tool: 
![image](https://user-images.githubusercontent.com/81352397/126893406-91622e27-4b9d-4ddb-85be-c2b2d603d0ba.png)

....still happening. Is there any way to convert them back to shaderlab(or maybe some dummy unity shaders to shaderlab)

**Comment by ds5678** [comment]
This is two issues in one. In the future, please post separate issues.

CAB files: I have not yet explored any of the file parsing, so I don't currently know enough to give an educated answer.

Shaders: Full shader reconstruction is extremely difficult and might never be a part of this project. However, I do plan on implementing some sort of dummy shader system to make things more user friendly. These dummy shaders would be very simple, intended only to avoid shader compiling issues.

**Comment by ds5678** [comment]
Dummy shaders were implemented a while ago.

In `0.1.5.1`, I implemented DXDecompiler as a replacement for HLSLccWrapper. It can occasionally export a decompiled shader rather than a disassembled shader.

If there is still a use for and a problem with importing CAB files, please feel free to post a new issue.
