### ISSUE TITLE
[Enhancement]: Genshin Impact 2.0 Version Update support

### ISSUE THREAD

**Issue by bc15kle** [ds5678/AssetRipper#68]
### Describe the new feature or enhancement

With the newest update releasing (version 2.1) of Genshin Impact, do you think it would be possible to add support to Genshin Impact 2.0? 
There's an edited assetstudio version support Genshin Impact 2.0 and I am wondering if AssetRipper will at some point support it too.

**Comment by ds5678** [comment]
I have no interest in targeting a specific game.
