### ISSUE TITLE
Monoscripts and Monobehavious still missing

### ISSUE THREAD

**Issue by DatTaiwanGuy** [ds5678/AssetRipper#7]
### Are you on the latest version of AssetRipper?

- [X] Yes, I'm on the latest version of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

Game: MEGAMAN X DiVE( US Ver.)
Engine Ver: Unity 2018.4.27f1
Platform: Android/iOS

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

I've already tested the pre-release version of your ripper in safe mode because of my RAM memory and i have some few problems about the monoscripts and monobehaviours again, when it had finished exporting, it gave me empty scripts
[Scripts.zip](https://github.com/ds5678/AssetRipper/files/6876438/Scripts.zip)

...also some of the script components are missing from the extracted project, yet i have every script dumped from ill2cpp dumper and also ill2cpp inspector, and still it's not detecting anything.

Is there anything wrong?

P.S I extracted the whole bunch of C.A.B files including the folders with ill2cpp dumped scripts(except for some dragonbones, ui and jsondatas from the assets cause it almost took 15.5 GB of my hard drive)which took over 5.9 GB RAM memory.

### Relevant log output

[Uploading AssetRipper.log…]()

**Comment by ds5678** [comment]
Can you reupload the log? The link is broken

**Comment by DatTaiwanGuy** [comment]
[AssetRipper log file.zip](https://github.com/ds5678/AssetRipper/files/6876651/AssetRipper.log.file.zip)

**Comment by ds5678** [comment]
Thank you. It's really late in my timezone. I'll take a closer look in the morning

**Comment by ds5678** [comment]
A couple things I noticed:
* Your scripts are not empty. They are stripped of everything but their serializable fields.
* Your missing scripts are most likely caused by imperfect IL2Cpp dumping. If the assembly isn't there for AssetRipper to read, then the scripts will be missing.
* AssetRipper did not recognize your game as Android. It seems that you selected 6000 files for ripping instead of the folder that contains them.

**Comment by DatTaiwanGuy** [comment]
....cause some CAB files are from the game server that i decrypted and decompressed.....

**Comment by ds5678** [comment]
Whenever you drop a bunch of files like that into AssetRipper, it treats them as unstructured
