### ISSUE TITLE
[Enhancement]: Optimize Script Export

### ISSUE THREAD

**Issue by ds5678** [ds5678/AssetRipper#70]
### Describe the new feature or enhancement

Recently, the [ICSharpCode.Decompiler](https://www.nuget.org/packages/ICSharpCode.Decompiler) package was implemented for exporting scripts (#65). This offers durable and efficient decompiling without maintaining a decompiler. However, the package was hastily implemented into the new exporter for early testing. As a result, it exports slowly and needs optimized for performance.

**Comment by ichalkorg** [comment]
please open your email from me, help me

**Comment by ichalkorg** [comment]
my email : ichalkorg@gmail.com

**Comment by ichalkorg** [comment]
I have sent a message to you

**Comment by ds5678** [comment]
@ichalkorg stop it. You've been spamming this repository and my personal email. That is not appropriate behavior. If you have an issue, post an issue. Spamming will get you nowhere.

**Comment by ds5678** [comment]
With 93dc394ac06ac47110ade45b4150f878034b8248, full script decompilation is as optimized as it can be with about 97% of the time spent inside the ILSpy decompiler.

However, decompile time might be further improved by sacrifices such as the stubbing/stripping described in #69.
