### ISSUE TITLE
[Other]: Project decompiled fine but..

### ISSUE THREAD

**Issue by Proigr3** [ds5678/AssetRipper#72]
### Describe the issue

AssetRipping a project went fine but, almost all scripts are missing their "insides", like there'd be a script that's supposed to have hundreds of lines, but is empty. Only "usings" and inheritance is there. Is this a bug, or just a limitation?

Project I was trying to rip was IL2CPP compiled, does that make it not work?

**Comment by ds5678** [comment]
Try the latest alpha

**Comment by Proigr3** [comment]
> Try the latest alpha
Thank you for replying, but where do I find the latest alpha? Im kinda new to github

**Comment by Proigr3** [comment]
Ok, tried ripping the project again with the latest alpha version, that I got from the link above. It got further, now names of functions appeared, more variables did aswell. But the functions are empty, or incomplete. Example:
`public bool MotorsEnabled => default(bool);

public float PropellantTech => default(float);

public VehicleEra(string eraName, float technologyFactor, float turretTraverseResistanceCoeff)
{
}

public VehicleEra Copy()
{
	return null;
}

public static float GetLinearDrag(float techFactor)
{
	return default(float);
}`

**Comment by ds5678** [comment]
I just wrote a detailed issue explaining this situation. #74
