### ISSUE TITLE
[Bug]: not same Export file

### ISSUE THREAD

**Issue by rasior27** [ds5678/AssetRipper#76]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2019.4.29f1

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

This on on asets ripper had mesh 31
![image](https://user-images.githubusercontent.com/89815485/132046731-3ef6c7dc-9e51-4d27-be12-8325e0cf7371.png)

but when export only 17
![image](https://user-images.githubusercontent.com/89815485/132046656-48b42b9d-a0a1-4cc9-9ab1-ef9408e63d3d.png)

and folder not same like assets ripper view 
![image](https://user-images.githubusercontent.com/89815485/132047248-27c8a7bf-be3f-4b54-972a-4992faf21dde.png)

**Comment by ds5678** [comment]
Hi, this is a known issue. Assets only get exported if something depends on them.

**Comment by ds5678** [comment]
Closing because we discovered that #81 was the source of your issue
