### ISSUE TITLE
[Bug]: Failed to load game content

### ISSUE THREAD

**Issue by SuperQuoc** [ds5678/AssetRipper#77]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

I don't know.

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

I got this message:

Failed to load game content: Access to the path 'C:\Users\XXX\Desktop\Game\assets\bin\Data' is denied.

**Comment by ds5678** [comment]
Hi, this bug has already been resolved in the alpha builds. You can either use the latest alpha build (there download links in the README), or you can wait for the next release.
