### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Piepop101** [ds5678/AssetRipper#80]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2019.4.21f1

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

While it is incredible that I was able to restore from an old built file for Blade and Sorcery VR, it was not perfect.  As you can see in this video, the ground is invisible and for some reason there is a bug that causes certain things to only appear at a certain angle with the camera: https://streamable.com/75cpyo (Look at the statue on the right).  The rip also doesn't save the script data, so while placing the ripped scene, it only shows the scripts as: "Missing Mono Script"

It is a start though since previous versions of asset ripped could not open Blade and Sorcery .bundles

1) Clipping meshs/Objects(Not sure which)
2) Missing Mono Scripts

**Comment by ds5678** [comment]
Without your `AssetRipper.log` file, I cannot debug the problem.

**Comment by Piepop101** [comment]
[AssetRipper.log](https://github.com/ds5678/AssetRipper/files/7150188/AssetRipper.log)

**Comment by Piepop101** [comment]
The Tailed Beast Temple is what I am having an issue with. The Apok was a test that I didn't expect to work.

**Comment by ds5678** [comment]
1. This is a known issue that's being investigated.
2. Your game was not presented to AssetRipper in such a way that it could find the game assemblies.

**Comment by ds5678** [comment]
This was resolved in 78eace3caedbae057ddd79860da556212b04f8dd
