### ISSUE TITLE
[Bug]: Retro's Basics in Fun Activites Open Source Edition in near avaliable

### ISSUE THREAD

**Issue by bnmtyhgunec1** [ds5678/AssetRipper#83]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

2019.3.0a5

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

RBIFA OSE in the
![Banickate's Basics_ The 6 Maps 1 10 2020 11_04_35](https://user-images.githubusercontent.com/90337933/133088897-a9e291ab-d887-400f-bfe5-4c2eaa83c43b.png)
 near avaliable

### Relevant log output

1234
![Banickate's Basics_ The 6 Maps 1 10 2020 11_04_35](https://user-images.githubusercontent.com/90337933/133088947-6565b02d-f5e7-48ad-93b1-309d132ee21e.png)

**Comment by ds5678** [comment]
I need your `AssetRipper.log` file
