### ISSUE TITLE
[Bug]: Performance on some large games

### ISSUE THREAD

**Issue by Blightbuster** [ds5678/AssetRipper#88]
### Describe the new feature or enhancement

Hey,
using uTinyRipper and now this fork is always a pleasure but its unfortunate that exporting large games can take well over 12h (Escape from Tarkov, i7-4790k, 860evo). I've noticed that the CPU as well as drive is never really utilized to its max potential so I assume there is no parallelization / concurrency going on. Especially (i assume) sequential exporting of small meshes takes a huge chunk of time while only utilizing about 15% CPU and at most 0.2 MB/s on the drive.

Is there anything preventing [this](https://github.com/ds5678/AssetRipper/blob/eaf052000df30088b8dd20462aa1eb9150d53a4d/AssetRipperCore/Project/ProjectExporter.cs#L187) from using something like `System.Threading.Tasks.Parallel.ForEach`? Is this even the bottleneck im experiencing?

**Comment by ds5678** [comment]
I'm not sure why you would be experiencing such a wait. In most cases, AssetRipper is substantially faster than uTiny. 

The only notable exception is script export. Assetripper uses the ILSpy decompiler which gives full decompilation, but is slower than uTiny's primitive decompiler.

**Comment by Blightbuster** [comment]
Just tried again with the latest release version:
The "Preparing for Export" step is already running for 1,5 hours and reduced the used RAM from 18,2 GB to 6,7 GB with CPU utilization being at around 20% for the whole time.

**Comment by Blightbuster** [comment]
Last few lines from the output:
```
18:44:41: General : About to begin export to C:\test
18:44:41: General : Removing any files from a previous export...
18:44:41: Export : Attempting to export assets to C:\test...
18:44:41: Export : Exporting to Unity version 2018.4.28f1
18:44:41: Export : Preparing for export...
18:44:53: Import [Warning] : Assembly 'Sirenix.OdinInspector.Editor' hasn't been found
18:44:53: Import [Warning] : Assembly 'UnityEngine.TestRunner' hasn't been found
18:44:53: Import [Warning] : Assembly 'UnityEngine.GoogleAudioSpatializer' hasn't been found
18:44:53: Import [Warning] : Assembly 'Unity.Recorder.Tests' hasn't been found
18:44:53: Import [Warning] : Assembly 'com.unity.cinemachine.Tests' hasn't been found
18:44:53: Import [Warning] : Assembly 'Unity.TextMeshPro.Tests' hasn't been found
18:44:53: Import [Warning] : Assembly 'Unity.Postprocessing.Runtime.Tests' hasn't been found
18:44:53: Import [Warning] : Assembly 'Sirenix.Utilities.Editor' hasn't been found
```

**Comment by Blightbuster** [comment]
With the new version, the actual export was a lot faster. Only about 40min. Great! Hopefully the preparing stuff can be optimized but thats its already a great improvement over uTinyRippers speed.

**Comment by ds5678** [comment]
I'm glad it's going well for you
