### ISSUE TITLE
Failed to load game content: Error during reading of asset type Mesh

### ISSUE THREAD

**Issue by Th3Nigh7mare** [ds5678/AssetRipper#91]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

Phasmo version

### Is the game Mono or IL2Cpp?

Yep

### Describe the issue.

Failed to load game content: Error during reading of asset type Mesh

**Comment by SamboyCoding** [comment]
I had encountered this issue last night and a fix for it was put in https://github.com/ds5678/AssetRipper/commit/6ce0c72a3c2816b57af89f514eefd82f689436eb . Can you try again with the latest alpha build?
