### ISSUE TITLE
[Other]: Can't open

### ISSUE THREAD

**Issue by 1669614244** [ds5678/AssetRipper#93]
### Describe the issue

Can't open AssetRipperConsole_win64
AssetRipperGUI_win64  Can't open  VRChat  __data
Failed to load game content: Some data left

**Comment by ds5678** [comment]
AssetRipperConsole is a console application which means it's meant to be ran in a command prompt. AssetRipperGUI has a graphical user interface and is meant to be opened normally.

As for your extraction problem, the AssetRipper team does not offer technical support for ripping VR Chat or content intended for VR Chat.
