### ISSUE TITLE
[Bug]: Access Denied for folder Data

### ISSUE THREAD

**Issue by cyberangel67** [ds5678/AssetRipper#95]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which Unity version did this occur on?

unknown this is an android zip file

### Is the game Mono or IL2Cpp?

Mono

### Describe the issue.

Failed to load game content: Access to the path '............\assets\bin\Data' is denied.

I have been able to extract this in AssetStudio 0.15.32

**Comment by ds5678** [comment]
I need to see the log. This should be solved in `0.1.6.0`

**Comment by cyberangel67** [comment]
Looks like it is, hmm, sorry I thought I had that version installed.
